import './globals.css'
import ReactQuery from './util/ReactQuery/ReactQuery'
import DarkMode from '@/components/Common/DarkMode/DarkMode'
import DarkModeProviders from '@/components/Common/DarkMode/DarkModeProvider'
import Footers from '@/components/Common/Footers'
import Headers from '@/components/Common/Headers'
import TopButton from '@/components/Common/TopButton'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <DarkModeProviders>
      <Headers />
      <ReactQuery>
        {children}
      </ReactQuery>
      <Footers />
      <DarkMode />
      <TopButton />
      </DarkModeProviders>
      </body>
    </html>
  )
}
