import './globals.css'
import ReactQuery from './util/ReactQuery/ReactQuery'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ReactQuery>
        {children}
      </ReactQuery>
      </body>
    </html>
  )
}
